language:  php

php:
  - '7.2'
  - '7.3'
  - '7.4'

# before_install:

install:
  - git clone -b enigma972-user-bundle https://github.com/enigma972/symfony-testing-package user-bundle
  - cd user-bundle
  - composer install

script: php bin/phpunit